name: builder
version: 0.0.1
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-builder
description: Library to support more sophisticated build scripts
dependencies:
  unittest: any
